{{- if .Values.components.cliInjector.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fno.fullname" . }}-cli-injector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fno.labels" . | nindent 4 }}
    app: cli-injector
spec:
  selector:
    matchLabels:
      {{- include "fno.selectorLabels" . | nindent 6 }}
      app: cli-injector
  template:
    metadata:
      labels:
        {{- include "fno.selectorLabels" . | nindent 8 }}
        app: cli-injector
    spec:
      serviceAccountName: {{ include "fno.serviceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodePoolLabelKey }}
                    operator: Exists
      containers:
        - name: cli-injector
          securityContext:
            runAsUser: 0
          image: {{ include "fno.image" . }}
          command:
            - /usr/local/bin/fake-cli-injector
          args:
            - "--host-path"
            - "/opt/fake-network-operator/bin/"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-bin
              mountPath: /opt/fake-network-operator/bin/
          resources:
            {{- toYaml .Values.components.cliInjector.resources | nindent 12 }}
      volumes:
        - name: host-bin
          hostPath:
            path: /opt/fake-network-operator/bin/
{{- end }}
