//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentToggle) DeepCopyInto(out *ComponentToggle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentToggle.
func (in *ComponentToggle) DeepCopy() *ComponentToggle {
	if in == nil {
		return nil
	}
	out := new(ComponentToggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsSpec) DeepCopyInto(out *ComponentsSpec) {
	*out = *in
	if in.NicLabeler != nil {
		in, out := &in.NicLabeler, &out.NicLabeler
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.RDMADevicePlugin != nil {
		in, out := &in.RDMADevicePlugin, &out.RDMADevicePlugin
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.SRIOVDevicePlugin != nil {
		in, out := &in.SRIOVDevicePlugin, &out.SRIOVDevicePlugin
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.SRIOVConfigDaemon != nil {
		in, out := &in.SRIOVConfigDaemon, &out.SRIOVConfigDaemon
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.StatusExporter != nil {
		in, out := &in.StatusExporter, &out.StatusExporter
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.CLIInjector != nil {
		in, out := &in.CLIInjector, &out.CLIInjector
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.IBKubernetes != nil {
		in, out := &in.IBKubernetes, &out.IBKubernetes
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.UFMStub != nil {
		in, out := &in.UFMStub, &out.UFMStub
		*out = new(ComponentToggle)
		**out = **in
	}
	if in.AdmissionWebhook != nil {
		in, out := &in.AdmissionWebhook, &out.AdmissionWebhook
		*out = new(ComponentToggle)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsSpec.
func (in *ComponentsSpec) DeepCopy() *ComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNicClusterPolicy) DeepCopyInto(out *FakeNicClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNicClusterPolicy.
func (in *FakeNicClusterPolicy) DeepCopy() *FakeNicClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(FakeNicClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNicClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNicClusterPolicyList) DeepCopyInto(out *FakeNicClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FakeNicClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNicClusterPolicyList.
func (in *FakeNicClusterPolicyList) DeepCopy() *FakeNicClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(FakeNicClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNicClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNicClusterPolicySpec) DeepCopyInto(out *FakeNicClusterPolicySpec) {
	*out = *in
	if in.NicNodePools != nil {
		in, out := &in.NicNodePools, &out.NicNodePools
		*out = make(map[string]NicNodePoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Components.DeepCopyInto(&out.Components)
	if in.SecondaryNetworks != nil {
		in, out := &in.SecondaryNetworks, &out.SecondaryNetworks
		*out = make([]SecondaryNetworkSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNicClusterPolicySpec.
func (in *FakeNicClusterPolicySpec) DeepCopy() *FakeNicClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FakeNicClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNicClusterPolicyStatus) DeepCopyInto(out *FakeNicClusterPolicyStatus) {
	*out = *in
	if in.AppliedNodePools != nil {
		in, out := &in.AppliedNodePools, &out.AppliedNodePools
		*out = make(map[string]NodePoolStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ComponentStatuses != nil {
		in, out := &in.ComponentStatuses, &out.ComponentStatuses
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNicClusterPolicyStatus.
func (in *FakeNicClusterPolicyStatus) DeepCopy() *FakeNicClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FakeNicClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicNodePoolSpec) DeepCopyInto(out *NicNodePoolSpec) {
	*out = *in
	if in.NICs != nil {
		in, out := &in.NICs, &out.NICs
		*out = make([]NicSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicNodePoolSpec.
func (in *NicNodePoolSpec) DeepCopy() *NicNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NicNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicSpec) DeepCopyInto(out *NicSpec) {
	*out = *in
	if in.RDMA != nil {
		in, out := &in.RDMA, &out.RDMA
		*out = new(RDMASpec)
		**out = **in
	}
	if in.SRIOV != nil {
		in, out := &in.SRIOV, &out.SRIOV
		*out = new(SRIOVSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicSpec.
func (in *NicSpec) DeepCopy() *NicSpec {
	if in == nil {
		return nil
	}
	out := new(NicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolStatus) DeepCopyInto(out *NodePoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolStatus.
func (in *NodePoolStatus) DeepCopy() *NodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDMASpec) DeepCopyInto(out *RDMASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDMASpec.
func (in *RDMASpec) DeepCopy() *RDMASpec {
	if in == nil {
		return nil
	}
	out := new(RDMASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRIOVSpec) DeepCopyInto(out *SRIOVSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRIOVSpec.
func (in *SRIOVSpec) DeepCopy() *SRIOVSpec {
	if in == nil {
		return nil
	}
	out := new(SRIOVSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryNetworkSpec) DeepCopyInto(out *SecondaryNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryNetworkSpec.
func (in *SecondaryNetworkSpec) DeepCopy() *SecondaryNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(SecondaryNetworkSpec)
	in.DeepCopyInto(out)
	return out
}
