{{- if .Values.components.sriovConfigDaemon.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fno.fullname" . }}-sriov-config-daemon
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fno.labels" . | nindent 4 }}
    app: sriov-config-daemon
spec:
  selector:
    matchLabels:
      {{- include "fno.selectorLabels" . | nindent 6 }}
      app: sriov-config-daemon
  template:
    metadata:
      labels:
        {{- include "fno.selectorLabels" . | nindent 8 }}
        app: sriov-config-daemon
    spec:
      serviceAccountName: {{ include "fno.serviceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodePoolLabelKey }}
                    operator: Exists
      containers:
        - name: sriov-config-daemon
          image: {{ include "fno.image" . }}
          command:
            - /usr/local/bin/fake-sriov-config-daemon
          args:
            - "--topology-namespace"
            - {{ .Values.namespace | quote }}
            - "--node-name"
            - "$(NODE_NAME)"
            {{- if .Values.components.sriovConfigDaemon.args }}
            {{- toYaml .Values.components.sriovConfigDaemon.args | nindent 12 }}
            {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.components.sriovConfigDaemon.resources | nindent 12 }}
{{- end }}
